#!/usr/bin/env php
<?php
require __DIR__ . '/app/bootstrap.php';

use Marvin\Commands\CreateApacheCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CreateApacheCommand($container));
$application->run();