#!/usr/bin/env php
<?php
require __DIR__ . '/app/bootstrap.php';

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}

use Marvin\Commands\CreateApacheCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CreateApacheCommand($container));
$application->run();